name: real_estate_ui
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.9
  intl: ^0.18.1
  clipboard: ^0.1.3
  flutter_staggered_grid_view: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.1.5
  kiwi_generator: ^4.0.1
  objectbox_generator: ^2.3.1

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/svg/
    - assets/images/

  fonts:
    - family: RedHatText
      fonts:
        - asset: assets/fonts/RedHatText-Bold.ttf
          weight: 700
        - asset: assets/fonts/RedHatText-BoldItalic.ttf
          style: italic
          weight: 700
        - asset: assets/fonts/RedHatText-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/RedHatText-Medium.ttf
          weight: 500
        - asset: assets/fonts/RedHatText-Regular.ttf
          weight: 400
        - asset: assets/fonts/RedHatText-Light.ttf
          weight: 300

    - family: BarlowCondensed
      fonts:
        - asset: assets/fonts/BarlowCondensed-Bold.ttf
          weight: 700
        - asset: assets/fonts/BarlowCondensed-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/BarlowCondensed-Medium.ttf
          weight: 500
        - asset: assets/fonts/BarlowCondensed-Regular.ttf
          weight: 400
        - asset: assets/fonts/BarlowCondensed-Light.ttf
          weight: 300
